pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh "ls"
            }
        }
        stage('list') {
            steps {
                sh "ls"
            }
        }
        stage('post') {
            steps {
                sh "echo 'hello world'"
            }
        }
    }
}
